version: '2'

services:

  #########################################################
  ## APP: core
  #########################################################

  core:
    image: node
    ports:
      - "3000:3000"
    links:
      - rabbitmq
    volumes:
      - ./core:/app
    working_dir: /app/
    command: npm start
    environment:
      AMQP: amqp://rabbit:pass@rabbitmq


  #########################################################
  ## APP: worker.user
  #########################################################

  worker.user:
    image: node
    links:
      - rabbitmq
      - neo4j
    volumes:
      - ./worker.user:/app
    working_dir: /app/
    command: npm start
    environment:
      AMQP: amqp://rabbit:pass@rabbitmq
      NEO4J_HOST: bolt://neo4j
      NEO4J_USER: neo4j
      NEO4J_PASS: pass


  #########################################################
  ## DB: redis
  #########################################################

  redis:
    image: redis
    ports:
      - "6379:6379"


  #########################################################
  ## DB: neo4j
  #########################################################

  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
    environment:
      NEO4J_AUTH: "neo4j/pass"


  #########################################################
  ## AMQP: rabbitmq
  #########################################################

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "pass"

