version: '2'

services:

  #########################################################
  ## APP: core
  #########################################################

  core:
    image: node
    ports:
      - "3000:3000"
    links:
      - postgres
      - rabbitmq
      - redis
    volumes:
      - ./core:/app
    working_dir: /app/
    command: npm start
    environment:
      AMQP: amqp://rabbit:pass@rabbitmq
      POSTGRES: postgres://postgres:pass@postgres/bunch
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FB_CLIENT: 1002150193167658
      FB_SECRET: 5407ca311e24cc72c133a74e01778b6c


  #########################################################
  ## APP: worker
  #########################################################

  worker:
    image: node
    links:
      - postgres
      - rabbitmq
      - neo4j
    volumes:
      - ./worker:/app
    working_dir: /app/
    command: npm start
    environment:
      AMQP: amqp://rabbit:pass@rabbitmq
      POSTGRES: postgres://postgres:pass@postgres/bunch
      NEO4J_HOST: bolt://neo4j
      NEO4J_USER: neo4j
      NEO4J_PASS: pass


  #########################################################
  ## DB: postgres
  #########################################################

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bunch


  #########################################################
  ## DB: redis
  #########################################################

  redis:
    image: redis
    ports:
      - "6379:6379"


  #########################################################
  ## DB: neo4j
  #########################################################

  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
    environment:
      NEO4J_AUTH: "neo4j/pass"


  #########################################################
  ## AMQP: rabbitmq
  #########################################################

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "pass"

